import localFont from "next/font/local";
import { Silkscreen, Sixtyfour, Raleway } from 'next/font/google';
import ThemeProvider from './theme_provider'
import "./globals.css";

	
const silkscreen = Silkscreen({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-silkscreen',
  });

  const sixtyfour= Sixtyfour({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-sixtyfour',
  });

  const raleway= Raleway({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-raleway',
  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${silkscreen.variable} ${sixtyfour.variable} ${raleway.variable} antialiased`}>
              <ThemeProvider>{children}</ThemeProvider>    
      </body>
    </html>
  );
}

